export const UPDATE_LIQUID = 'UPDATE_LIQUID'
export const UPDATE_CPU_STAKED = 'UPDATE_CPU_STAKED'
export const UPDATE_NET_STAKED = 'UPDATE_NET_STAKED'
export const UPDATE_RAM_STAKED = 'UPDATE_RAM_STAKED'
