export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO'
export const GET_ACCOUNT_INFO_SUCCESS = 'GET_ACCOUNT_INFO_SUCCESS'
export const GET_ACCOUNT_INFO_FAILED = 'GET_ACCOUNT_INFO_FAILED'

export const SHOW_TRANSFER_VIEW = 'SHOW_TRANSFER_VIEW'
export const SHOW_TRANSFER_VIEW_SUCCESS = 'SHOW_TRANSFER_VIEW_SUCCESS'
export const SHOW_TRANSFER_VIEW_FAILED = 'SHOW_TRANSFER_VIEW_FAILED'

export const CLOSE_TRANSFER_VIEW = 'CLOSE_TRANSFER_VIEW'
export const CLOSE_TRANSFER_VIEW_SUCCESS = 'CLOSE_TRANSFER_VIEW_SUCCESS'
export const CLOSE_TRANSFER_VIEW_FAILED = 'CLOSE_TRANSFER_VIEW_FAILED'

export const GET_TOKENS = 'GET_TOKENS'
export const GET_TOKENS_SUCCESS = 'GET_TOKENS_SUCCESS'
export const GET_TOKENS_FAILED = 'GET_TOKENS_FAILED'

export const TRANSFER_TOKENS = 'TRANSFER_TOKENS'
export const TRANSFER_TOKENS_SUCCESS = 'TRANSFER_TOKENS_SUCCESS'
export const TRANSFER_TOKENS_FAILED = 'TRANSFER_TOKENS_FAILED'
