export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO'
export const GET_ACCOUNT_INFO_SUCCESS = 'GET_ACCOUNT_INFO_SUCCESS'
export const GET_ACCOUNT_INFO_FAILED = 'GET_ACCOUNT_INFO_FAILED'

export const REFRESH_ACCOUNT_INFO = 'REFRESH_ACCOUNT_INFO'
export const REFRESH_ACCOUNT_INFO_SUCCESS = 'REFRESH_ACCOUNT_INFO_SUCCESS'
export const REFRESH_ACCOUNT_INFO_FAILED = 'REFRESH_ACCOUNT_INFO_FAILED'

export const SHOW_TRANSFER_VIEW = 'SHOW_TRANSFER_VIEW'
export const SHOW_TRANSFER_VIEW_SUCCESS = 'SHOW_TRANSFER_VIEW_SUCCESS'
export const SHOW_TRANSFER_VIEW_FAILED = 'SHOW_TRANSFER_VIEW_FAILED'

export const CLOSE_TRANSFER_VIEW = 'CLOSE_TRANSFER_VIEW'
export const CLOSE_TRANSFER_VIEW_SUCCESS = 'CLOSE_TRANSFER_VIEW_SUCCESS'
export const CLOSE_TRANSFER_VIEW_FAILED = 'CLOSE_TRANSFER_VIEW_FAILED'

export const SHOW_REGISTER_STEP = 'SHOW_REGISTER_STEP'
export const SHOW_REGISTER_STEP_SUCCESS = 'SHOW_REGISTER_STEP_SUCCESS'
export const SHOW_REGISTER_STEP_FAILED = 'SHOW_REGISTER_STEP_FAILED'

export const CLOSE_REGISTER_STEP = 'CLOSE_REGISTER_STEP'
export const CLOSE_REGISTER_STEP_SUCCESS = 'CLOSE_REGISTER_STEP_SUCCESS'
export const CLOSE_REGISTER_STEP_FAILED = 'CLOSE_REGISTER_STEP_FAILED'

export const SHOW_LOCK_SCREEN = 'SHOW_LOCK_SCREEN'
export const SHOW_LOCK_SCREEN_SUCCESS = 'SHOW_LOCK_SCREEN_SUCCESS'
export const SHOW_LOCK_SCREEN_FAILED = 'SHOW_LOCK_SCREEN_FAILED'

export const CLOSE_LOCK_SCREEN = 'CLOSE_LOCK_SCREEN'
export const CLOSE_LOCK_SCREEN_SUCCESS = 'CLOSE_LOCK_SCREEN_SUCCESS'
export const CLOSE_LOCK_SCREEN_FAILED = 'CLOSE_LOCK_SCREEN_FAILED'

export const GET_TOKENS = 'GET_TOKENS'
export const GET_TOKENS_SUCCESS = 'GET_TOKENS_SUCCESS'
export const GET_TOKENS_FAILED = 'GET_TOKENS_FAILED'

export const TRANSFER_TOKENS = 'TRANSFER_TOKENS'
export const TRANSFER_TOKENS_SUCCESS = 'TRANSFER_TOKENS_SUCCESS'
export const TRANSFER_TOKENS_FAILED = 'TRANSFER_TOKENS_FAILED'

export const UPDATE_EOS_PROVIDER = 'UPDATE_EOS_PROVIDER'
export const UPDATE_EOS_PROVIDER_SUCCESS = 'UPDATE_EOS_PROVIDER_SUCCESS'
export const UPDATE_EOS_PROVIDER_FAILED = 'UPDATE_EOS_PROVIDER_FAILED'
